### ISSUE TITLE
Identical rules in sample-rulesystem-setup.sql

### ISSUE THREAD

**Issue by calvincodes** [kislayverma/Rulette#59]
Steps to reproduce:
1. Create a sample rule-system using the `sample-rulesystem-setup.sql` script.
2. Run `SimpleMysqlUse` class.
3. Prints the following error:
```
[main] INFO com.github.kislayverma.rulette.example.mysql.SimpleMysqlUse - ==========Update a rule==========
Exception in thread "main" java.lang.Exception: The rule to be deleted and the rule found are not the same.Something went horribly wrong
	at com.github.kislayverma.rulette.engine.impl.trie.TrieBasedEvaluationEngine.deleteRule(TrieBasedEvaluationEngine.java:157)
	at com.github.kislayverma.rulette.RuleSystem.updateRule(RuleSystem.java:240)
	at com.github.kislayverma.rulette.example.mysql.SimpleMysqlUse.updateRule(SimpleMysqlUse.java:129)
	at com.github.kislayverma.rulette.example.mysql.SimpleMysqlUse.runSamples(SimpleMysqlUse.java:110)
	at com.github.kislayverma.rulette.example.mysql.SimpleMysqlUse.run(SimpleMysqlUse.java:46)
	at com.github.kislayverma.rulette.example.mysql.SimpleMysqlUse.main(SimpleMysqlUse.java:35)
```

From my debugging, I believe the cause of this to be these identical rules in `sample-rulesystem-setup.sql` script:
`(192,'WES',3,NULL,NULL,NULL,'4'),(196,'WES',3,NULL,NULL,NULL,'4')`

Proposed fix: Use `NULL` as the `source_state` for ruleId 196.

**Comment by calvincodes** [comment]
If this is a genuine bug, then the above PR should fix this. :)
Also, in that case, it should be checked why is Rulette not throwing an exception while loading the rule engine with identical rules.

**Comment by kislayverma** [comment]
@calvincodes You are right! This can fix the temporary issue. The bigger issue now is why Rulette was able to load the ruleset at all
